language: ruby
rvm:
  - 2.3.1
services:
  - redis-server
before_install:
  - gem update --system
before_script:
  - cp config/settings.yml.travis config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rails test
addons:
  postgresql: "9.3"
git:
  submodules: false
sudo: false
cache: bundler
